// App configuration: where to reach the signaling server and which ICE
// (STUN/TURN) servers to use for WebRTC NAT traversal.
//
// You normally do NOT edit this file. Pass values at launch instead:
//
//   flutter run \
//     --dart-define=SIGNALING_URL=wss://your-app.onrender.com \
//     --dart-define=TURN_URL=turn:your-turn-host:3480 \
//     --dart-define=TURN_USER=your-username \
//     --dart-define=TURN_PASS=your-credential
//
// - SIGNALING_URL: the wss:// URL of your deployed Render service.
//     Local same-WiFi testing instead: ws://<your-computer-LAN-IP>:8080
//     Android emulator -> host machine: ws://10.0.2.2:8080 (the default).
// - TURN_*: from your free Metered account (or any TURN provider). REQUIRED for
//     two phones on different networks; without it, cross-network calls fail.
//     Not needed when both phones are on the same WiFi (STUN alone works).
//     TURN_URL may be a single URL or a comma-separated list (multiple
//     ports/transports improve reliability on restrictive networks).

class AppConfig {
  static const String signalingUrl = String.fromEnvironment(
    'SIGNALING_URL',
    defaultValue: 'ws://10.0.2.2:8080',
  );

  static const String _turnUrl = String.fromEnvironment('TURN_URL');
  static const String _turnUser = String.fromEnvironment('TURN_USER');
  static const String _turnPass = String.fromEnvironment('TURN_PASS');

  static List<Map<String, dynamic>> get iceServers {
    final servers = <Map<String, dynamic>>[
      // Free public STUN — enough on the same network.
      {
        'urls': [
          'stun:stun.l.google.com:19302',
          'stun:stun1.l.google.com:19302',
        ],
      },
    ];

    // TURN relay — added only when credentials are provided. Required for
    // phones on different networks (different cities / cellular data).
    if (_turnUrl.isNotEmpty) {
      final urls = _turnUrl
          .split(',')
          .map((u) => u.trim())
          .where((u) => u.isNotEmpty)
          .toList();
      servers.add({
        'urls': urls,
        'username': _turnUser,
        'credential': _turnPass,
      });
    }

    return servers;
  }

  /// True when a TURN relay is configured. The UI can warn if it's missing and
  /// the phones aren't on the same network.
  static bool get hasTurn => _turnUrl.isNotEmpty;
}
